require_relative 'token/base'
require_relative 'token/eos'
require_relative 'token/space'
require_relative 'token/new_line'
require_relative 'token/word'
require_relative 'token/number'
require_relative 'token/punctuation'

require_relative 'token/chunk'
require_relative 'token/email'
require_relative 'token/url'
require_relative 'token/exception'
require_relative 'token/tag'
require_relative 'token/entity'
require_relative 'token/focus'
require_relative 'token/command'